[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."poll-scores"]
  schedule = "*/10 * * * *"

[functions."send-reminders"]
  schedule = "0 * * * *"
